/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konversilatihan1gui;

/**
 *
 * @author ASUS
 */
public class KonversiSuhuLat1 extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhuLat1
     */
    public KonversiSuhuLat1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogHasil = new javax.swing.JDialog();
        judulDialog = new javax.swing.JLabel();
        besaranSuhu = new javax.swing.JLabel();
        satuanSuhu = new javax.swing.JLabel();
        labelSamaDengan = new javax.swing.JLabel();
        besaranKonversi = new javax.swing.JLabel();
        satuanKonversi = new javax.swing.JLabel();
        dialogEror = new javax.swing.JDialog();
        labelEror = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        inputSuhu = new javax.swing.JTextField();
        labelDariSuhu = new javax.swing.JLabel();
        labelInputSuhu = new javax.swing.JLabel();
        labelKeSuhu = new javax.swing.JLabel();
        temperaturDari = new javax.swing.JComboBox<>();
        temperaturKe = new javax.swing.JComboBox<>();
        tblKonversi = new javax.swing.JButton();

        judulDialog.setFont(new java.awt.Font("SimSun", 0, 48)); // NOI18N
        judulDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulDialog.setText("HASIL KONVERSI");

        besaranSuhu.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        besaranSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        besaranSuhu.setText("jLabel2");

        satuanSuhu.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        satuanSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        satuanSuhu.setText("jLabel3");

        labelSamaDengan.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        labelSamaDengan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSamaDengan.setText("=");

        besaranKonversi.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        besaranKonversi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        besaranKonversi.setText("jLabel5");

        satuanKonversi.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        satuanKonversi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        satuanKonversi.setText("jLabel6");

        javax.swing.GroupLayout dialogHasilLayout = new javax.swing.GroupLayout(dialogHasil.getContentPane());
        dialogHasil.getContentPane().setLayout(dialogHasilLayout);
        dialogHasilLayout.setHorizontalGroup(
            dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogHasilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dialogHasilLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(besaranSuhu)
                .addGap(43, 43, 43)
                .addComponent(satuanSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(labelSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(besaranKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(satuanKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        dialogHasilLayout.setVerticalGroup(
            dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHasilLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(judulDialog)
                .addGap(55, 55, 55)
                .addGroup(dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(besaranSuhu)
                    .addComponent(satuanSuhu)
                    .addComponent(labelSamaDengan)
                    .addComponent(besaranKonversi)
                    .addComponent(satuanKonversi))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        labelEror.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        labelEror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEror.setText("TIDAK BOLEH DENGAN SATUAN YANG SAMA");

        javax.swing.GroupLayout dialogErorLayout = new javax.swing.GroupLayout(dialogEror.getContentPane());
        dialogEror.getContentPane().setLayout(dialogErorLayout);
        dialogErorLayout.setHorizontalGroup(
            dialogErorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogErorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogErorLayout.setVerticalGroup(
            dialogErorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogErorLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(labelEror)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("STHupo", 0, 48)); // NOI18N
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul.setText("Konversi Suhu");

        inputSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuhuActionPerformed(evt);
            }
        });

        labelDariSuhu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelDariSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDariSuhu.setText("Dari");

        labelInputSuhu.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelInputSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInputSuhu.setText("Input Suhu");

        labelKeSuhu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelKeSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKeSuhu.setText("Ke");

        temperaturDari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Reaumur", "Fahrenheit", "Kelvin" }));

        temperaturKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Reaumur", "Fahrenheit", "Kelvin" }));

        tblKonversi.setText("Konversi Suhu");
        tblKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKonversiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(tblKonversi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelInputSuhu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDariSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(labelKeSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(temperaturDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(temperaturKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelInputSuhu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDariSuhu)
                    .addComponent(labelKeSuhu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperaturDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperaturKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(tblKonversi)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuhuActionPerformed

    private void tblKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKonversiActionPerformed
        // TODO add your handling code here:
        double suhu = Double.valueOf(inputSuhu.getText());
        String tempDari = this.temperaturDari.getSelectedItem().toString();
        String tempKe = this.temperaturKe.getSelectedItem().toString();
        double hitung = 0;
        String satuan1= null;
        String satuan2 = null;
        
        if (tempDari.equals("Celcius")){
            if(tempKe.equals("Celcius")){
                this.labelEror.setVisible(true);
                this.dialogEror.setSize(480, 240);
                this.dialogEror.setVisible(true);
            }
            else if(tempKe.equals("Reaumur")){
                hitung = suhu * 4 / 5;
                satuan1 = " °C";
                satuan2 = " °R";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Fahrenheit")) {
                hitung = (suhu * 9 / 5) + 32;
                satuan1 = " °C";
                satuan2 = " °F";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
                
            }else if (tempKe.equals("Kelvin")) {
                hitung = suhu + 273;
                satuan1 = " °C";
                satuan2 = " K";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }
        }
        
        else if(tempDari.equals("Reaumur")){
            if(tempKe.equals("Reaumur")){
                this.labelEror.setVisible(true);
                this.dialogEror.setSize(480, 240);
                this.dialogEror.setVisible(true);
            }
            else if(tempKe.equals("Celcius")) {
                hitung = 5/4 + suhu;
                satuan1 = " °R";
                satuan2 = " °C";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Fahrenheit")) {
                hitung = (9/4 * suhu) + 32;
                satuan1 = " °R";
                satuan2 = " °F";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Kelvin")) {
                hitung = (5/4 * suhu) + 273;
                satuan1 = " °R";
                satuan2 = " K";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }
        }
        
        else if(tempDari.equals("Fahrenheit")){
            if(tempKe.equals("Fahrenheit")){
                this.labelEror.setVisible(true);
                this.dialogEror.setSize(480, 240);
                this.dialogEror.setVisible(true);
            }
            else if (tempKe.equals("Celcius")) {
                hitung = 5 / 9 * (suhu - 32);
                satuan1 = " °F";
                satuan2 = " °C";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Reaumur")) {
                hitung = 4 / 9 * (suhu - 32);
                satuan1 = " °F";
                satuan2 = " °R";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Kelvin")) {
                hitung = 5 / 9 * (suhu - 32) + 273;
                satuan1 = " °F";
                satuan2 = " °C";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }
        }
        
        else if(tempDari.equals("Kelvin")){
            if(tempKe.equals("Kelvin")){
                this.labelEror.setVisible(true);
                this.dialogEror.setSize(480, 240);
                this.dialogEror.setVisible(true);
            }
            if(tempKe.equals("Celcius")){
                hitung = suhu - 273;
                satuan1 = " K"; 
                satuan2 = " °C";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Reaumur")) {
                hitung = 4 / 5 * (suhu - 273);
                satuan1 = " K";
                satuan2 = " °C";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }else if (tempKe.equals("Fahrenheit")) {
                hitung = 9 / 5 * (suhu - 273) + 32;
                satuan1 = " K";
                satuan2 = " °F";
                this.besaranSuhu.setText(String.valueOf(suhu));
                this.satuanSuhu.setText(satuan1);
                this.besaranKonversi.setText(String.valueOf(hitung));
                this.satuanKonversi.setText(satuan2);
                this.dialogHasil.setSize(480, 240);
                this.dialogHasil.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_tblKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuLat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuLat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuLat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuLat1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuLat1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel besaranKonversi;
    private javax.swing.JLabel besaranSuhu;
    private javax.swing.JDialog dialogEror;
    private javax.swing.JDialog dialogHasil;
    private javax.swing.JTextField inputSuhu;
    private javax.swing.JLabel judulDialog;
    private javax.swing.JLabel labelDariSuhu;
    private javax.swing.JLabel labelEror;
    private javax.swing.JLabel labelInputSuhu;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKeSuhu;
    private javax.swing.JLabel labelSamaDengan;
    private javax.swing.JLabel satuanKonversi;
    private javax.swing.JLabel satuanSuhu;
    private javax.swing.JButton tblKonversi;
    private javax.swing.JComboBox<String> temperaturDari;
    private javax.swing.JComboBox<String> temperaturKe;
    // End of variables declaration//GEN-END:variables
}
