/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.konversitemperature;

/**
 *
 * @author ASUS
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogHasil = new javax.swing.JDialog();
        judulDialog = new javax.swing.JLabel();
        besaranCelcius = new javax.swing.JLabel();
        satuanCelcius = new javax.swing.JLabel();
        labelSamaDengan = new javax.swing.JLabel();
        besaranKonversi = new javax.swing.JLabel();
        satuanKonversi = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        labelCelcius = new javax.swing.JLabel();
        labelUbah = new javax.swing.JLabel();
        tblKonversi = new javax.swing.JButton();
        temperature = new javax.swing.JComboBox<>();
        inputCelcius = new javax.swing.JTextField();
        logoUns = new javax.swing.JLabel();

        judulDialog.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        judulDialog.setText("Hasil Konversi");

        besaranCelcius.setText("jLabel3");

        satuanCelcius.setText("jLabel6");

        labelSamaDengan.setText("=");

        besaranKonversi.setText("jLabel8");

        satuanKonversi.setText("jLabel9");

        javax.swing.GroupLayout dialogHasilLayout = new javax.swing.GroupLayout(dialogHasil.getContentPane());
        dialogHasil.getContentPane().setLayout(dialogHasilLayout);
        dialogHasilLayout.setHorizontalGroup(
            dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHasilLayout.createSequentialGroup()
                .addGroup(dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogHasilLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(judulDialog))
                    .addGroup(dialogHasilLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(besaranCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(satuanCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(labelSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(besaranKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(satuanKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        dialogHasilLayout.setVerticalGroup(
            dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHasilLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(judulDialog)
                .addGap(38, 38, 38)
                .addGroup(dialogHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(besaranCelcius)
                    .addComponent(satuanCelcius)
                    .addComponent(labelSamaDengan)
                    .addComponent(besaranKonversi)
                    .addComponent(satuanKonversi))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelJudul.setText("Konversi Temperature");

        labelCelcius.setText("Derajat Celcius");

        labelUbah.setText("Ubah Ke");

        tblKonversi.setText("Konversi");
        tblKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKonversiActionPerformed(evt);
            }
        });

        temperature.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelvin", "Fahrenheit", "Reaumur" }));

        logoUns.setIcon(new javax.swing.ImageIcon("D:\\ZZZ Yosef\\00 Koleyah\\Semester 3\\Praktikum Pemrograman 1\\Pertemuan 6 (Selasa, 3 Oktober 2023)\\KonversiTemperature\\src\\main\\java\\com\\mycompany\\konversitemperature\\Praktikum Pemrograman Selasa, 3 Oktober 2023.png")); // NOI18N
        logoUns.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudul)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(temperature, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputCelcius))))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(tblKonversi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(logoUns, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(logoUns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCelcius)
                    .addComponent(inputCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUbah)
                    .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(tblKonversi)
                .addGap(24, 24, 24))
        );

        labelJudul.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKonversiActionPerformed
        // TODO add your handling code here:
        double celcius = Double.valueOf(inputCelcius.getText());
        String temp = temperature .getSelectedItem().toString();
        double hitung = 0;
        String satuan = null;
        
        if(temp.equals("Kelvin")){
            hitung = celcius+273;
            satuan = "K";
        } else if(temp.equals("Reaumur")){
            hitung = celcius*4/5;
            satuan = " °R";
        } else if (temp.equals("Fahrenheit")){
            hitung = (celcius*9/5)+32;
            satuan = " °F";
        }
        
        besaranCelcius.setText(String.valueOf(celcius));
        satuanCelcius.setText("°C");
        besaranKonversi.setText(String.valueOf(hitung));
        satuanKonversi.setText(satuan);
        dialogHasil.setSize(480, 240);
        dialogHasil.setVisible(true);
    }//GEN-LAST:event_tblKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel besaranCelcius;
    private javax.swing.JLabel besaranKonversi;
    private javax.swing.JDialog dialogHasil;
    private javax.swing.JTextField inputCelcius;
    private javax.swing.JLabel judulDialog;
    private javax.swing.JLabel labelCelcius;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelSamaDengan;
    private javax.swing.JLabel labelUbah;
    private javax.swing.JLabel logoUns;
    private javax.swing.JLabel satuanCelcius;
    private javax.swing.JLabel satuanKonversi;
    private javax.swing.JButton tblKonversi;
    private javax.swing.JComboBox<String> temperature;
    // End of variables declaration//GEN-END:variables
}
